---

- name: Upgrade installed packages
  apt:
    upgrade: yes
  tags:
  - apt
  - upgrade

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - apt
    - cleanup

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  tags:
  - apt
  - cleanup

- name: Install GPG keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://download.sublimetext.com/sublimehq-pub.gpg"

- name: Add specified repositories into sources list using specified filename
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime

- name: Install packages
  apt:
    state: present
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - "sublime-text"
