---

- name: Add PPA required for Alacritty
  tags: terminal
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present

- name: Install Alacritty (Terminal Emulator)
  tags: terminal
  apt:
    pkg: alacritty
    state: latest

- name: Install Byobu (shell multiplexer)
  tags: terminal
  apt:
    pkg: byobu
    state: latest
