---
- name: Ansible Playbook to setup my laptop running Pop-OS
  hosts: popos
  become: true
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    cntb_version : "v1.3.0"
    opt_folder : "/opt"

  roles:
    - { role: roles/commons, become: yes, tags: ['commons'] }
    - { role: roles/development, become: yes, tags: [ 'development' ] }
    - { role: roles/deployment, become: yes, tags: [ 'deployment' ] }
    - { role: roles/communication, become: yes, tags: [ 'chat', 'communication' ] }
    #- { role: databases, become: yes, tags: [ 'db', 'dev' ] }
    #- { role: documentation, become: yes, tags: [ 'docs' ] }
    #- { role: fonts, become: yes, tags: [ 'fonts' ] }
    #- { role: geerlingguy.docker, become: yes, tags: [ 'containers', 'dev' ] }
    #- { role: git, become: yes, tags: [ 'git' ] }
    #- { role: graphics, become: yes, tags: [ 'graphics' ] }
    #- { role: java, become: yes, tags: [ 'dev', 'java' ] }
    #- { role: multimedia, become: yes, tags: [ 'audio', 'video' ] }
    #- { role: productivity, become: yes, tags: [ 'productivity' ] }
    #- { role: python, become: yes, tags: [ 'dev', 'python' ] }
  tasks:
    - debug: msg="You are running this Playbook as user {{ lookup('env','USER') }}"